using Microsoft.EntityFrameworkCore;

namespace FlowInn.API.Models
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder) 
        {
            modelBuilder.Entity<Category>().HasData(
                new Category { Id = 1, Name = "Active Wear" },
                new Category { Id = 2, Name = "Mens Fashion" },
                new Category { Id = 3, Name = "Womens Fashion" },
                new Category { Id = 4, Name = "GTA V Accessories" },
                new Category { Id = 5, Name = "Footwear" }
                );

            modelBuilder.Entity<Product>().HasData(
                
                new Product { Id = 1, CategoryId = 1, Name = "Sweat Band", Sku = "AWMGSJ", value = 68, Description="A band to be worn to keep sweat out of your eyes", IsAvailable = true},
                new Product { Id = 2, CategoryId = 2, Name = "Suit", Sku = "LSOEID", value = 200, Description = "Stylish overcoat", IsAvailable = false },
                new Product { Id = 3, CategoryId = 3, Name = "Leggings", Sku = "CNUSTS", value = 50, Description = "For the legs", IsAvailable = true },
                new Product { Id = 4, CategoryId = 4, Name = "Junk Energy Inductor", Sku = "IUYTRD", value = 6800, Description = "The best accessory", IsAvailable = true },
                new Product { Id = 5, CategoryId = 5, Name = "Nikes", Sku = "DNCJHS", value = 50, Description = "Shoes for your feet", IsAvailable = true },
                new Product { Id = 6, CategoryId = 1, Name = "Joggers", Sku = "POIUDS", value = 20, Description = "Pants", IsAvailable = true },
                new Product { Id = 7, CategoryId = 2, Name = "Tie", Sku = "DJKSLE", value = 30, Description = "Stylish", IsAvailable = true },
                new Product { Id = 8, CategoryId = 3, Name = "Makeup", Sku = "MCJDES", value = 150, Description = "For the face", IsAvailable = true },
                new Product { Id = 9, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 10, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 11, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 12, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 13, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 14, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 15, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 16, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 17, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 18, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 19, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 20, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 21, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 22, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 23, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 24, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 25, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 26, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 27, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 28, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 29, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 30, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 31, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 32, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 33, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 34, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 35, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 36, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 37, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 38, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 39, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 40, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 41, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 42, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 43, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 44, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 45, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 46, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 47, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 48, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 49, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 50, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 51, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 52, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 53, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 54, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 55, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 56, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 57, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 58, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 59, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 60, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 61, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 62, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 63, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 64, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 65, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 66, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 67, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 68, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 69, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 70, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 71, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 72, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 73, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 74, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 75, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 76, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 77, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 78, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 79, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 80, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 81, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 82, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 83, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 84, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 85, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 86, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 87, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 88, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 89, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 90, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 91, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 92, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 93, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 94, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 95, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 96, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 97, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 98, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 99, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 100, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 101, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 102, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 103, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 104, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 105, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 106, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 107, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 108, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 109, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 110, CategoryId = 4, Name = "bat", Sku = "DOEPSD", value = 45, Description = "For baseball", IsAvailable = true },
                new Product { Id = 111, CategoryId = 5, Name = "Adidas", Sku = "ALZWMC", value = 41, Description = "Shoes for your feet", IsAvailable = true });
        }
    }
}
